import { config } from 'dotenv';
config();
export const dbUri = process.env.MONGO_URI;
export const port = process.env.PORT || 5000;
export const jwtSecret = process.env.JWT_SECRET;
export const dbName = process.env.DB_NAME;
export const secretKey = process.env.SECRET_KEY;
export const refreshTokenExpirationTime = 7 * 24 * 60 * 60 * 1000;
export const frontendUri = process.env.FRONTEND_URL;
export const environment = process.env.NODE_ENV;
export const wmateClientId = process.env.WMATE_CLIENT_ID;
export const wmateClientSecret = process.env.WMATE_CLIENT_SECRET;
export const instanceId = process.env.INSTANCE_ID;
export const groupAdminNumber = process.env.GROUP_ADMIN_NUMBER;
export const groupName = process.env.GROUP_NAME;