# name: Deploy Main Branch to Prod Server

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: SSH into Prod Server and Deploy
#         uses: appleboy/ssh-action@v1
#         with:
#           host: ${{ secrets.PROD_SERVER_HOST }}
#           username: ${{ secrets.PROD_SERVER_USERNAME }}
#           key: ${{ secrets.PROD_SERVER_SSH_KEY }}
#           script: |
#             cd /path/to/your/project
#             git fetch origin
#             git checkout main
#             git pull origin main
#             npm install
#             pm2 restart your-app-name