# name: Deploy Feature Branch to UAT Server

# on:
#   push:
#     branches:
#       - feature-branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: SSH into UAT Server and Deploy
#         uses: appleboy/ssh-action@v1
#         with:
#           host: ${{ secrets.UAT_SERVER_HOST }}
#           username: ${{ secrets.UAT_SERVER_USERNAME }}
#           key: ${{ secrets.UAT_SERVER_SSH_KEY }}
#           script: |
#             cd /path/to/your/project
#             git fetch origin
#             git checkout feature-branch
#             git pull origin feature-branch
#             npm install
#             pm2 restart your-app-name